import copy
import json
import re
from pathlib import Path

import sleap_io as sio
from sleap_io.io.coco import convert_labels
from sleap_io.io.dlc import is_dlc_file

_EMPTY_LABELS_ERROR_MSG = {
    "default": (
        "No annotations could be extracted from the input file. "
        "Please check that the input file contains labeled frames. "
    ),
    "dlc": (
        "Ensure that the paths to the labelled frames are in the "
        "standard DLC project format: "
        "labeled-data / <video-name> / "
        "<filename-with-frame-number>.<extension> "
        "and that the frames files exist."
    ),
}


def annotations_to_coco(
    input_path: Path,
    output_json_path: Path,
    *,
    coco_image_filenames: str | list[str] | None = None,
    coco_visibility_encoding: str = "ternary",
) -> Path:
    """Export annotations file to COCO format.

    Parameters
    ----------
    input_path : pathlib.Path
        Path to the input annotations file.
    output_json_path : pathlib.Path
        Path to save the output COCO JSON file.
    coco_image_filenames : str | list[str] | None, optional
        Optional image filenames to use in the COCO JSON. If provided,
        must be a single string (for single-frame videos) or a list of
        strings matching the number of labeled frames. If None (default),
        generates filenames from video filenames and frame indices.
    coco_visibility_encoding : str, optional
        Encoding scheme for keypoint visibility in the COCO JSON file.
        Options are "ternary" (0: not labeled, 1: labeled but not visible,
        2: labeled and visible) or "binary" (0: not visible, 1: visible).
        Default is "ternary".

    Returns
    -------
    pathlib.Path
        Path to the saved COCO JSON file.

    Notes
    -----
    The format of the input annotations file is automatically inferred based
    on its extension. See :func:`sleap_io.io.main.load_file` for supported
    formats.

    Example
    -------
    >>> from pathlib import Path
    >>> from poseinterface.io import annotations_to_coco
    >>> coco_json_path = annotations_to_coco(
    ...     input_path=Path("path/to/annotations.slp"),
    ...     output_json_path=Path("path/to/annotations_coco.json"),
    ... )
    """
    labels = sio.load_file(input_path)

    # Check if labels object is empty
    if len(labels.labeled_frames) == 0:
        error_msg = _EMPTY_LABELS_ERROR_MSG["default"]
        if is_dlc_file(input_path):
            error_msg += _EMPTY_LABELS_ERROR_MSG["dlc"]
        raise ValueError(error_msg)

    # Generate COCO dict from sleap-io
    coco_data = convert_labels(
        labels,
        image_filenames=coco_image_filenames,
        visibility_encoding=coco_visibility_encoding,
    )

    # Update image ids to reflect frame number,
    # and annotation and category ids to be 0-based.
    update_ids(coco_data, output_json_path)

    return output_json_path


def update_ids(data: dict, output_file: Path) -> Path:
    """Update the ids of the data in the input COCO JSON file.

    In the output file:
    - the image ids are derived from the filename, and
    - the annotation and category ids are 0-based following
    the order they appear in their respective lists.

    Parameters
    ----------
    data : dict
        Dictionary containing the COCO data, generated by sleap-io.
    output_file : pathlib.Path
        Path to save the updated frame labels file.

    Returns
    -------
    pathlib.Path
        Path to the updated frame labels file.
    """
    # Update image, annotation and category ids:
    # - image IDs are derived from the filename
    # - annotation and category IDs are 0-based following
    # the order they appear in their respective lists
    data_updated = data
    for update_fn in [
        _update_image_ids,
        _update_annotation_ids,
        _update_category_ids,
    ]:
        data_updated = update_fn(data_updated)

    # Save json
    with open(output_file, "w") as f:
        json.dump(data_updated, f)

    return output_file


def _extract_image_id_from_filename(filename: str) -> int | None:
    """Extract the image id from the filename.

    The frame number is expected to be the group of digits after "frame-"
    in the filename, preceded by at least one zero. If no frame number
    is found, returns None.
    """
    match = re.search(r"frame-(0\d*)", filename)
    if match is None:
        raise ValueError(
            "No frame number could be extracted from filename "
            f"{filename}. Please check that the filename contains a "
            "frame number after 'frame-' and is preceded by at least one zero."
        )
    return int(match.group(1))


def _update_image_ids(input_data: dict) -> dict:
    """Assigns image ids based on frame number from filename."""
    # Compute map old to new ID
    old_to_new_id = {
        img["id"]: _extract_image_id_from_filename(img["file_name"])
        for img in input_data["images"]
    }

    # Check new IDs are unique
    # TODO: add issue to move to the validator in the future
    if len(old_to_new_id) != len(set(old_to_new_id.values())):
        raise ValueError(
            "Extracted image IDs are not unique. Please check that the frame "
            "numbers as specified in the filename are unique."
        )

    # Create new dict
    data = copy.deepcopy(input_data)

    # Update image IDs
    for img in data["images"]:
        img["id"] = old_to_new_id[img["id"]]

    # Update image_id in annotations list
    for annot in data["annotations"]:
        annot["image_id"] = old_to_new_id[annot["image_id"]]

    return data


def _update_annotation_ids(input_data: dict) -> dict:
    """Assigns 0-based ids to the annotations.

    Ids are assigned in the order the annotations appear
    in the list.
    """
    data = copy.deepcopy(input_data)
    for i, annot in enumerate(data["annotations"]):
        annot["id"] = i
    return data


def _update_category_ids(input_data: dict) -> dict:
    """Assigns 0-based ids to the categories.

    Ids are assigned in the order the categories appear
    in the list.
    """
    # Compute map old to new ID for categories
    old_to_new_id = {
        cat["id"]: i for i, cat in enumerate(input_data["categories"])
    }

    # Create new dict
    data = copy.deepcopy(input_data)

    # Assign id in categories list
    for cat in data["categories"]:
        cat["id"] = old_to_new_id[cat["id"]]

    # Update category_id in annotations list
    for annot in data["annotations"]:
        annot["category_id"] = old_to_new_id[annot["category_id"]]

    return data
