import copy
import json
import re
from pathlib import Path

import sleap_io as sio
from sleap_io.io.coco import convert_labels
from sleap_io.io.dlc import is_dlc_file

_EMPTY_LABELS_ERROR_MSG = {
    "default": (
        "No annotations could be extracted from the input file. "
        "Please check that the input file contains labeled frames. "
    ),
    "dlc": (
        "Ensure that the paths to the labelled frames are in the "
        "standard DLC project format: "
        "labeled-data / <video-name> / "
        "<filename-with-frame-number>.<extension> "
        "and that the frames files exist."
    ),
}


def annotations_to_coco(
    input_path: Path,
    output_json_path: Path,
    *,
    frame_regexp: str = r"img(0\d*)",
    coco_image_filenames: str | list[str] | None = None,
    coco_visibility_encoding: str = "ternary",
) -> Path:
    """Export annotations file to COCO format for poseinterface.

    Parameters
    ----------
    input_path : pathlib.Path
        Path to the input annotations file.
    output_json_path : pathlib.Path
        Path to save the output COCO JSON file.
    frame_regexp: str, optional
        Regular expression pattern to extract the frame number from the image
        filename as stated in the input annotations file. By default,
        the frame number is expected to be the group of
        digits after "img" in the filename, preceded by at least one zero.
    coco_image_filenames : str | list[str] | None, optional
        Optional image filenames to use in the COCO JSON. If provided,
        must be a single string (for single-frame videos) or a list of
        strings matching the number of labeled frames. If None (default),
        generates filenames from video filenames and frame indices.
    coco_visibility_encoding : str, optional
        Encoding scheme for keypoint visibility in the COCO JSON file.
        Options are "ternary" (0: not labeled, 1: labeled but not visible,
        2: labeled and visible) or "binary" (0: not visible, 1: visible).
        Default is "ternary".

    Returns
    -------
    pathlib.Path
        Path to the saved COCO JSON file.

    Notes
    -----
    The format of the input annotations file is automatically inferred based
    on its extension. See :func:`sleap_io.io.main.load_file` for supported
    formats.

    In the poseinterface COCO output file, the image IDs correspond to the
    frame numbers and are derived from the image filenames. The annotation and
    category ids are 0-based indices.

    Example
    -------
    >>> from pathlib import Path
    >>> from poseinterface.io import annotations_to_coco
    >>> coco_json_path = annotations_to_coco(
    ...     input_path=Path("path/to/annotations.slp"),
    ...     output_json_path=Path("path/to/annotations_coco.json"),
    ... )
    """
    labels = sio.load_file(input_path)

    # Check if labels object is empty
    if len(labels.labeled_frames) == 0:
        error_msg = _EMPTY_LABELS_ERROR_MSG["default"]
        if is_dlc_file(input_path):
            error_msg += _EMPTY_LABELS_ERROR_MSG["dlc"]
        raise ValueError(error_msg)

    # Generate COCO dict from sleap-io
    coco_data = convert_labels(
        labels,
        image_filenames=coco_image_filenames,
        visibility_encoding=coco_visibility_encoding,
    )

    # Update image ids to reflect frame number
    update_ids(coco_data, output_json_path, frame_regexp)

    return output_json_path


def update_ids(data: dict, output_file: Path, frame_regexp: str) -> Path:
    """Update the image IDs of the data in the input COCO JSON file.

    The new image IDs are derived from the frame
    number in the filename, using the provided regular expression pattern.

    Parameters
    ----------
    data : dict
        Dictionary containing the COCO data, generated by sleap-io.
    output_file : pathlib.Path
        Path to save the updated frame labels file.
    frame_regexp : str
        Regular expression pattern to extract the frame number from the image
        filename. By default, the frame number is expected to be the group of
        digits after "img" in the filename, preceded by at least one zero.

    Returns
    -------
    pathlib.Path
        Path to the updated frame labels file.
    """
    data_updated = _update_image_ids(data, frame_regexp)

    with open(output_file, "w") as f:
        json.dump(data_updated, f)

    return output_file


def _update_image_ids(input_data: dict, frame_regexp: str) -> dict:
    """Assigns new image IDs based on the frame number in the filename."""
    # Compute map old to new ID
    old_to_new_id = {
        img["id"]: _extract_frame_number(img["file_name"], frame_regexp)
        for img in input_data["images"]
    }

    # Check new IDs are unique
    if len(old_to_new_id) != len(set(old_to_new_id.values())):
        raise ValueError(
            "Extracted image IDs are not unique. Please check that the frame "
            "numbers as specified in the filename are unique."
        )

    # Create new dict
    data = copy.deepcopy(input_data)

    # Update image IDs
    for img in data["images"]:
        img["id"] = old_to_new_id[img["id"]]

    # Update image_id in annotations list
    for annot in data["annotations"]:
        annot["image_id"] = old_to_new_id[annot["image_id"]]

    return data


def _extract_frame_number(filename: str, frame_regexp: str) -> int | None:
    """Extract the frame number in the input filename.

    If no frame number is found, returns None.
    """
    match = re.search(frame_regexp, filename)
    if match is None:
        raise ValueError(
            "No frame number could be extracted from filename "
            f"{filename}. Please check that the filename contains a "
            "frame number matching the provided regexp pattern "
            rf"{frame_regexp}."
        )
    return int(match.group(1))
